### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by dewhisna**
Merged the RPi cross-compile notes into the main README.

### CODE REVIEW

**Comment by kwagyeman** [comment]
Thanks for doing this.

**Comment by dewhisna** [comment]
No problem; you're welcome.  If you want my RPi build to post with your other downloads and installers so that everything can be found together in one place or to test out, I have it posted in my releases:
https://github.com/dewhisna/openmv-ide/releases/tag/v1.6.0-RPi

You should now have all the details you need for doing the RPi builds too.  I'll occasionally try to keep my repository fork sync'd and run a build for my own experimentation of OpenMV with the RPi setup in my lab, but I probably won't be able to keep up with every main release you guys do, so you'll probably want to take over building them.

Thanks for the OpenMV camera design and tool work you guys are doing.  It's off to a great start!

**Comment by kwagyeman** [comment]
Yes, I'll spin up some RPI VMs when I have a chance to take over building for it.

Also, checkout www.omniacreator.com. it's a project I started on a while back that didn't get popular, but, I'm going to integrate the tech into OpenMV IDE. So, soon you'll be able to create graphs on demand with your OpenMV Cam or any MP board.

**Comment by dewhisna** [comment]
OmniaCreator looks pretty interesting.  It seems very similar to one called Guino that I used and ported to Qt three or four years ago.  Their original Guino used OpenFrameworks and I ported it to Qt to make GuinoQt, making it more portable (though I'm not sure I ever got around to publishing my GuinoQt variant).  At the time I was using it on Linux, Mac, and the Raspberry Pi to do data visualization of libSVM (Support Vector Machine) pattern recognition for a swept-frequency capacitive touch/gesture sensor.  Believe it or not, it was actually an extension of the current project I'm working on where I'm now experimenting with OpenMV -- though in a completely different area of the project.

At the time, I was using an Alamode board on my Raspberry Pi for the Arduino side of it and was running the data graphing and rendering on the Raspberry Pi itself.  For my current project, I designed a "ProMini PiDuino HAT" board for the RPi (https://oshpark.com/shared_projects/8ydgt0rh) that I'm now using.  And for the more intense work for the project, I will be using the STM32F746G Discovery Board instead, as it has up to 2.4msps ADCs with DMA and lots of external RAM, plus with its LCD, I can do most of my graphing work on-board.

Here's the Guino links:
http://www.instructables.com/id/Guino-Dashboard-for-your-Arduino/
https://github.com/madshobye/guino

Sometime, I'll have to play around with OmniaCreator and see how they compare, and I look forward to seeing your integration with OpenMV.

Thanks!

**Comment by kwagyeman** [comment]
I'll probably work on that integration once there are a lot more users.

**Comment by kwagyeman** [comment]
Hi, I bought a raspberry Pi and can start building images for it now. However, I noticed that each PI version seems to need a different G++ library. Is this the case? I'm interested in releasing binary packages that can run on all PI versions that don't require any Qt libraries installed.

**Comment by dewhisna** [comment]
You'll need to compile it against a specific Qt and the end-user will need that version of Qt in some form.  The deployment package I made for the RPi was self-contained and had all of the Qt library pieces it used, that I had compiled for it, bundled with it so that the user didn't need to separately install Qt, and with the library search paths set to automatically find it in the bundle.

If you really don't want the separate Qt lib files in the bundle, you could compile a static version of Qt so that it links statically to the OpenMV application.  It's been a while since I've tried compiling Qt purely static.  From past experience, it can be sort of hit-or-miss.  Some Qt releases seem to work better than others for that and it also depended on the environment.  I don't think they fully test all of the static options.  For example, I was successful in statically compiling Qt 4.8.5 on a Mac, but I never could get Qt 5.5.1 to compile static on the Mac to save my life.  I finally decided that just including the individual dynamic library files in the same code bundle with a local library search path really wasn't much different than a static build, so I generally resolve to doing that.

As for "each Pi version seems to need a different G++ library", you'll need a specific sysroot image to use for your cross-compile.  If you dynamically link everything to the runtime, then the user's  sysroot will need to have a compatible runtime to the one you used.  If everything is built static, then it would only be bound to a specific kernel API, but still need to target a specific OS variant.  It's the same basic rules that apply when building apps for the desktop environment.  If you use a Jessie Raspbian, it probably won't work for users running a Wheezy Raspbian, for example, but you should be able to make it compatible across several release versions of Jessie.

As for targeting different RPi's, the key difference there is that the various RPi boards have different forms of the ARM micro, like A6 vs A7, etc.  There are different gcc code generation options for targeting them and Qt mkspecs to select which is used.  Generally, things built for RPi 2 will run on the better micro of the RPi 3, but not necessarily the other way around.  To put it in desktop terms, it's much like making a program that runs on a 386 and having it run on a 586, but if you target the 586, it may not run on the 386.  But the code can be better optimized for the features of the 586.

The instructions I had put together was targeting the RPi 2 and RPi 3 environments.  I haven't tried it on the RPi 1, but the build I did is likely using processor features the RPi 1 doesn't have since I used the "linux-rasp-pi2-g++" mkspec.  I figured OpenMV could benefit from the better processor options of the RPi 2, and plus most people using OpenMV will probably want at least an RPi 2 for performance anyway, so that was my logic there.  People really wanting it to run on an RPi 1 could compile it themselves and change up the device option to switch mkspecs.

**Comment by kwagyeman** [comment]
Hi, I've updated the build system to allow you to more easily build for the pi. Simply pass the argument "--rpi" to the make.py script followed by the path to the cross compile QTDIR. E.g.

./make.py --rpi /opt/qtrpi/raspi/qt5

I've also placed the output tar.gz file here:

http://upload.openmv.io/openmv-ide-linux-arm-1.7.1.tar/openmv-ide-linux-arm-1.7.1.tar.gz

Anyway, I think I've got the build part right, however, the IDE doesn't run on the PI. At least my Pi. I used the QtRpi thingy to install the cross compiler system. Its targeted using qt 5.7.0 and linux-rasp-pi2-g++.

Can you try out the bundle and see if it works? If not, any ideas on how to fix it?

(Also, mind emailing me so we can take this offline from this PR).

**Comment by kwagyeman** [comment]
Fixed the link.

**Comment by kwagyeman** [comment]
http://upload.openmv.io/openmv-ide-linux-arm-1.7.1/openmv-ide-linux-arm-1.7.1.tar.gz

Okay, this one is good.

**Comment by dewhisna** [comment]
I downloaded it.  However, the RPi I have to work on this project is in a state of flux at the moment, as I'm working on designing a laser vision system and that RPi is the brain for that project...

In the meantime, do try some of the other platform plugins.  Qt, by default on the RPi, uses the EGLFS plugin, which is designed for full-screen mode (the "FS" part) and I found that with the OpenMV IDE it will hang the system if you try to run it with an X-Windows session going -- or at least crash with lots of errors.

And if you want to run it stand-alone as the only app outside of X, you have to fix some libraries first.  Someone messed up the EGL/GLES libraries on the RPi image and built the packages with one that isn't compatible with the RPi codecs.  The wrong ones are in the /usr/lib/arm-linux-gnueabihf/ folder and the correct ones are in /opt/vc/lib/.  See the notes on item 8 in my ReadMe notes.  That is needed for the EGLFS mode to work, which should work if you exit X-windows.  Oh, and run "sudo ldconfig" after changing those symlinks.  I probably should have added that step to my ReadMe notes.

However, to make it run under X, I found that the xcb plugin worked decently well on mine.  Launch it from the command line with "./openmvide -platform xcb".  Of course for that to work, you had to compile in xcb support in your Qt, which requires a few additional libxcb dependencies.  I haven't checked your image yet to see if it had that plugin or not.  But that's what worked well on my system originally with my build.

Either way, I will try this version as soon as I can get my RPi functional again...

**Comment by kwagyeman** [comment]
I just get this issue for all platform plugins:

This application failed to start because it could not find or load the Qt platform plugin "eglfs"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted

With the text changing for the particular plugin I try. This error happens in the Qt low level code... before OpenMV IDE's code loads so it's hard to track down. That said, at least the app runs technically so it's an arm binary.

**Comment by kwagyeman** [comment]
Note that I'm VNC'ing into the Pi. I'm not sure what that means for a desktop environment.

**Comment by kwagyeman** [comment]
I fixed the path issues and used sudo ldconfig and I get the same error:

This application failed to start because it could not find or load the Qt platform plugin "eglfs"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted

**Comment by dewhisna** [comment]
Hmmm...  I don't think the eglfs plugin will work over vnc.  Of the ones in your list, I would try both the "xcb" and the "linuxfb".  I've done vnc before, but via in Qt 4.8.5 with the qws system -- even running in a "NoVNC" web socket setup (example: http://vnc.purebiblesearch.com/).  But I haven't used VNC much with Qt 5.

I would think a normal VNC setup where you are serving all of the X-Windows would work as a normal remote desktop and use one of the standard xcb or linuxfb plugins.  Another thing to try is using ssh with X forwarding enabled.  Then if you are running remotely on a machine with X-Windows support, like Linux, you should be able to have the RPi app run directly on your remote screen.  I do that all the time with my RPi's for running them headless.  Just add the "-X" option to ssh when you connect to the RPi.  I don't think that even requires running "xhost" and all of that to enable (but I can't remember)...

**Comment by kwagyeman** [comment]
I don't think VNC matters for viewing a windowed applciation. As for X11 forwarding over SSH. That fails too. I think there's something wrong with the binary but I don't know what. Since you have a working build it would be awesome if you could run my updated make.py script to see if that operational. Then I'll need to reinstall the qt cross compiler.

**Comment by dewhisna** [comment]
I just remembered I had another RPi 3 here that I was setting up for a laser cutter.  I used ssh with X11 forwarding to connect to it and tried your build and it does indeed run.  I had to use 'xcb', but it worked.  The only issue was that Qt doesn't ship fonts by default anymore.  I had previously done a patch to get them included in the tarball for my build, but it seems your tarball is missing them, so it spits out a ton of font errors and falls back to a default system font.

From my linux laptop, here's the steps I used:

```
$ ssh -X pi@192.168.1.2
pi:~ $ tar -zxf  openmv-ide-linux-arm-1.7.1.tar.gz
pi:~ $ cd ~/openmvide/bin
pi:~/openmvide/bin $ ./openmvide -platform xcb
```

And up it came in a window on my linux laptop.  The only change you should have to make is the IP address of your RPi.

I did try linuxfb and eglfs just to see what they'd do and neither of them work for two reasons -- 1) that RPi is running an X-server at the moment and 2) and they, at least the eglfs, work with OpenGL for the local hardware and don't do X11 forwarding over ssh.  eglfs is mostly for writing to a local monitor with hardware graphics acceleration.  The linuxfb plugin would probably work if you had a server running the frame buffer that could transport it.  But 'xcb' does do X11 and it worked via ssh forwarding mode...

Now, there were some wonky graphical issues with the IDE itself, which I think was because it was running remotely, but it came up and ran.  So I think (except for the missing fonts) your build is OK.  It's at least runnable.  If I can get a monitor and keyboard on one of those Pi's in the next couple of days, I'll confirm it by running it locally...

**Comment by kwagyeman** [comment]
Um, I have a Raspberry Pi 3 with no custom software on it. All I did was:

sudo apt-get update
sudo apt-get upgrade

So, its basically clean. Given that, the software fails to run. I did also do the lib eglfs fix and that didn't help. All platform plugin modes fail.

I'm thinking to distributing a setup.sh file and a run.sh file with the tar. Or editing the openmvide.sh file to check all things that need to be checked to make sure the IDE runs. I can easily generate these scripts with some python file I/O from the make.py script before OpenMV is Run. If you'd like to help me out getting this all working and verified I'd be happy to give you some free OpenMV Cams and other stuff.

**Comment by dewhisna** [comment]
Oh, I was just thinking... Unless you did a completely static build, you're going to need the minimal system dependencies installed that you had in your sysroot when compiling it -- system things that the Qt you built was compiled to use.  According to this (https://wiki.qt.io/RaspberryPi2EGLFS#Step_by_step) Qt blog, you can probably use:

```
sudo apt-get update
sudo apt-get build-dep qt4-x11
sudo apt-get build-dep libqt5gui5
sudo apt-get install libudev-dev libinput-dev libts-dev libxcb-xinerama0-dev libxcb-xinerama0
```

Now, you technically don't need the development versions of those packages installed to just run it, so you can drop all of the `-dev` suffixes.  And instead of the build-deps for Qt, as that's using, you just need the normal package dependencies.  You can get the dependency list with `apt-cache depends libqt5gui5`, for example.  But you will need to have all of the packages installed that the compiled version of Qt is linked with.

Another way would be to run `ldd` on every binary, starting with `openmvide` and working through each Qt lib, and find the libraries it's linking and every one that they are linking too, and use `apt-file find` to see which packages include them and use that to make your list of package dependencies.

There's probably better ways to do it, some utility that just gives you that package list perhaps, build I'm not as familiar with all of the system package building facilities.  Whenever I distribute desktop apps for Linux, I generally build them against LSB (Linux Standard Base) to make them platform independent so they will run on nearly every flavor of Linux without having to make a separate installer package for every distro.  But I don't know if the RPi supports LSB or not -- I've never tried.  I do see `lsb-release`, `lsb-core`, etc, packages in the apt cache on my RPi.  So it would seem that it does.

As for my helping you get it going, I wouldn't mind it, but at the moment, I'm so backlogged on projects I can't afford another distraction.  I'm desperately trying to get the first stage of this laser vision system functional by the end of the week of Labor Day.  So it will be at least a month before I'd have an opportunity.

**Comment by kwagyeman** [comment]
Definitely going to have to edit the openmvide.sh script to install all of this stuff. Okay, I think I should be able to get something working if I can figure out the differences. Luckily the default PI setup never asks for a password.

**Comment by kwagyeman** [comment]
I got it working with -platform xcb. Had to do... sudo apt-get install libxcb*...

Okay, so I can fix the font deploy problem. It seems like the qtrpi doesn't come with fonts at all.

But otherwise it works on the PI. However, it seems like I'll have to provide a script that does a lot of sudo apt gets...

**Comment by kwagyeman** [comment]
Hi, try the download again. http://upload.openmv.io/openmv-ide-linux-arm-1.7.1/openmv-ide-linux-arm-1.7.1.tar.gz

I think I've solved most of the issues... I just need to figure out what else needs to be in the setup.sh script. Will have to build a new fresh raspi disk image to test to see what's needed...

**Pull request merged**
